#!/usr/bin/env python3
"""Validate and atomically save the personal Hyprland hotkey, rolling back on errors."""
import argparse
import ctypes
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
BINARY = ROOT / "target/release/omaflow"

def config_path():
    return Path(os.environ.get("OMAFLOW_CONFIG", str(Path(os.environ.get("XDG_CONFIG_HOME", str(Path.home()/".config"))) / "omaflow/config.toml")))

def config_command(*args):
    return subprocess.run([str(BINARY), *args], capture_output=True, text=True, timeout=8, check=True).stdout


MODIFIERS = {"Shift_L": 1, "Shift_R": 1, "Control_L": 4, "Control_R": 4,
             "Alt_L": 8, "Alt_R": 8, "Super_L": 64, "Super_R": 64,
             "ISO_Level3_Shift": 128}


def parse_keys(value):
    keys = [key.strip() for key in re.split(r"[, +]+", value) if key.strip()]
    if len(keys) != len(set(keys)) or len(keys) > 4:
        raise ValueError("Choose up to four different keys")
    library = ctypes.CDLL("libxkbcommon.so.0")
    library.xkb_keysym_from_name.argtypes = [ctypes.c_char_p, ctypes.c_int]
    library.xkb_keysym_from_name.restype = ctypes.c_uint32
    for key in keys:
        if not re.fullmatch(r"[A-Za-z0-9_]+", key) or not library.xkb_keysym_from_name(key.encode(), 0):
            raise ValueError(f"Unknown XKB key: {key}. Try F9, F13, Control_L, Shift_L, or Menu.")
    return keys


def write_atomic(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=".omaflow-hotkey-", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as output:
            output.write(data)
            output.flush()
            os.fsync(output.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def run(*args):
    return subprocess.run(args, capture_output=True, text=True, timeout=8, check=True).stdout


def save(keys, consumed, write_only=False):
    if not keys:
        raise ValueError("Choose at least one trigger key")
    if any(key not in keys or key in MODIFIERS for key in consumed):
        raise ValueError("Reserved keys must be non-modifier keys in your shortcut")
    bindings = json.loads(run("hyprctl", "-j", "binds"))
    mask = 0
    for key in keys:
        mask |= MODIFIERS.get(key, 0)
    for binding in bindings:
        if "OmaFlow" in binding.get("description", ""):
            continue
        key = binding.get("key", "")
        if key in consumed or (key in keys and binding.get("modmask", 0) == mask):
            raise ValueError(f"{key} already controls {binding.get('description') or 'another Hyprland action'}. Choose a different key.")
    path = Path(os.environ.get("XDG_CONFIG_HOME", str(Path.home() / ".config"))) / "omaflow/shortcut.lua"
    personal = config_path()
    old_config = personal.read_bytes() if personal.exists() else None
    previous = path.read_bytes() if path.exists() else None
    content = ("-- Generated from omaflow/config.toml [shortcut]. Do not edit this file.\n"
               + "local omaflow_hotkey = { " + ", ".join(json.dumps(key) for key in keys) + " }\n"
               + "local omaflow_consumed_keys = { " + ", ".join(json.dumps(key) for key in consumed) + " }\n"
               + "return { hotkey = omaflow_hotkey, consumed = omaflow_consumed_keys }\n").encode()
    try:
        config_command("config-shortcut", json.dumps({"keys":keys,"consumed":consumed}))
        write_atomic(path, content)
        if not write_only:
            run("hyprctl", "reload")
            errors = run("hyprctl", "configerrors").strip()
            if errors:
                raise ValueError(errors)
    except Exception:
        if old_config is None:
            personal.unlink(missing_ok=True)
        else:
            write_atomic(personal, old_config)
        if previous is None:
            path.unlink(missing_ok=True)
        else:
            write_atomic(path, previous)
        if not write_only:
            run("hyprctl", "reload")
        raise
    return "Shortcut saved: " + " + ".join(keys)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--keys")
    parser.add_argument("--sync", action="store_true", help="validate and apply the TOML shortcut")
    parser.add_argument("--consumed", default="")
    parser.add_argument("--write-only", action="store_true")
    args = parser.parse_args()
    try:
        if args.sync:
            if args.keys:
                raise ValueError("Use --sync or --keys, not both")
            # Resolve defaults without changing the file before save() has
            # captured its rollback copy.
            config = json.loads(config_command("effective-config"))
            keys = config["shortcut"]["keys"]
            consumed = config["shortcut"]["consumed"]
            message = save(parse_keys(",".join(keys)), parse_keys(",".join(consumed)), args.write_only)
        elif args.keys:
            message = save(parse_keys(args.keys), parse_keys(args.consumed), args.write_only)
        else:
            raise ValueError("Use --keys or --sync")
        if not args.sync and not args.write_only:
            config_command("configure", "shortcut", json.dumps({"keys":parse_keys(args.keys),"consumed":parse_keys(args.consumed)}))
        print(json.dumps({"ok": True, "message": message}))
    except (OSError, ValueError, subprocess.SubprocessError) as error:
        print(json.dumps({"ok": False, "message": str(error)}))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
